# Atropos Recipe Configuration
# Based on VERL's recipe pattern, similar to DAPO

# Advantage weighting configuration
use_advantage_weighting: true
advantage_normalization: "batch"  # "none", "batch", "global"
advantage_clipping: [-5.0, 5.0]   # null for no clipping

# Model configuration
model:
  strategy: "fsdp"  # or "fsdp2"
  
# Data configuration  
data:
  micro_batch_size_per_gpu: 1
  balance_dp_token: true
  max_response_length: 512

# Optimizer configuration
optim:
  clip_grad: 1.0
  lr: 1.0e-5
  
# Sequence parallel configuration (if using)
ulysses_sequence_parallel_size: 1

# Logging configuration  
logging:
  level: "INFO" 